name: self-serve deployer

on:
  push:
    branches: [deploy-prod]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
        - uses: actions/checkout@v3
        - name: deploy and restart web server 
          run: |
            cd server
            npm i
            npm run start:prod
